service: kusoripu-twitter
provider:
  name: aws
  region: us-east-2
  timeout: 120

  environment:
    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}

package:
  exclude:
    - Dockerfile
    - docker-compose.yml

functions:
  api:
    runtime: python3.7
    handler: lambda_function.lambda_handler
    description: "twitter API"
    timeout: 60 
    layers:
      - arn:aws:lambda:us-east-2:719378226820:layer:twitter_api:1